import type { CasoBateria } from './tipos.js';

export const TERMINOS_SEMEJANTES: CasoBateria[] = [
  { id: 'ts-01', area: 'terminos-semejantes', antes: '3*x+2*x', despues: '5*x', espera: 'EQUIVALENTE' },
  { id: 'ts-02', area: 'terminos-semejantes', antes: '3*x+2*x', despues: '6*x', espera: 'NO_EQUIVALENTE', nota: 'multiplica los coeficientes' },
  { id: 'ts-03', area: 'terminos-semejantes', antes: '3*x+2*x', despues: '5*x^2', espera: 'NO_EQUIVALENTE', nota: 'suma tambien los exponentes' },
  { id: 'ts-04', area: 'terminos-semejantes', antes: '3*x+2*x-10', despues: '5*x-10', espera: 'EQUIVALENTE' },
  { id: 'ts-05', area: 'terminos-semejantes', antes: '3*x+2*x-10', despues: '-5*x', espera: 'NO_EQUIVALENTE', nota: 'junta el termino independiente con los de x' },
  { id: 'ts-06', area: 'terminos-semejantes', antes: '7*a-3*a', despues: '4*a', espera: 'EQUIVALENTE' },
  { id: 'ts-07', area: 'terminos-semejantes', antes: '7*a-3*a', despues: '4', espera: 'NO_EQUIVALENTE', nota: 'pierde la variable' },
  { id: 'ts-08', area: 'terminos-semejantes', antes: '2*x+3*y', despues: '5*x*y', espera: 'NO_EQUIVALENTE', nota: 'junta terminos que no son semejantes' },
  { id: 'ts-09', area: 'terminos-semejantes', antes: '2*x+3*y', despues: '5*x+y', espera: 'NO_EQUIVALENTE', nota: 'reparte mal los coeficientes' },
  { id: 'ts-10', area: 'terminos-semejantes', antes: 'x^2+3*x^2', despues: '4*x^2', espera: 'EQUIVALENTE' },
  { id: 'ts-11', area: 'terminos-semejantes', antes: 'x^2+3*x^2', despues: '4*x^4', espera: 'NO_EQUIVALENTE', nota: 'suma exponentes al sumar' },
  { id: 'ts-12', area: 'terminos-semejantes', antes: 'x^2+x^3', despues: 'x^5', espera: 'NO_EQUIVALENTE', nota: 'suma potencias distintas' },
  { id: 'ts-13', area: 'terminos-semejantes', antes: '5*x-8*x', despues: '-3*x', espera: 'EQUIVALENTE' },
  { id: 'ts-14', area: 'terminos-semejantes', antes: '5*x-8*x', despues: '3*x', espera: 'NO_EQUIVALENTE', nota: 'signo del resultado' },
  { id: 'ts-15', area: 'terminos-semejantes', antes: '4*x+3-2*x+7', despues: '2*x+10', espera: 'EQUIVALENTE' },
  { id: 'ts-16', area: 'terminos-semejantes', antes: '4*x+3-2*x+7', despues: '2*x-4', espera: 'NO_EQUIVALENTE', nota: 'aplica el menos tambien al 7' },
  { id: 'ts-17', area: 'terminos-semejantes', antes: '-x+x', despues: '0', espera: 'EQUIVALENTE' },
  { id: 'ts-18', area: 'terminos-semejantes', antes: '3*x*y+2*y*x', despues: '5*x*y', espera: 'EQUIVALENTE' },
  { id: 'ts-19', area: 'terminos-semejantes', antes: '2*a*b-a*b', despues: 'a*b', espera: 'EQUIVALENTE' },
  { id: 'ts-20', area: 'terminos-semejantes', antes: '2*a*b-a*b', despues: '2', espera: 'NO_EQUIVALENTE', nota: 'cancela las variables' },
];

export const DISTRIBUTIVA: CasoBateria[] = [
  { id: 'di-01', area: 'distributiva', antes: '2*(x+3)', despues: '2*x+6', espera: 'EQUIVALENTE' },
  { id: 'di-02', area: 'distributiva', antes: '2*(x+3)', despues: '2*x+3', espera: 'NO_EQUIVALENTE', nota: 'distribuye solo al primer termino' },
  { id: 'di-03', area: 'distributiva', antes: '-3*(x-4)', despues: '-3*x+12', espera: 'EQUIVALENTE' },
  { id: 'di-04', area: 'distributiva', antes: '-3*(x-4)', despues: '-3*x-12', espera: 'NO_EQUIVALENTE', nota: 'no cambia el signo del segundo termino' },
  { id: 'di-05', area: 'distributiva', antes: '-(x-3)', despues: '-x+3', espera: 'EQUIVALENTE' },
  { id: 'di-06', area: 'distributiva', antes: '-(x-3)', despues: '-x-3', espera: 'NO_EQUIVALENTE', nota: 'el menos delante del parentesis solo llega al primero' },
  { id: 'di-07', area: 'distributiva', antes: '5-(2*x-7)', despues: '12-2*x', espera: 'EQUIVALENTE' },
  { id: 'di-08', area: 'distributiva', antes: '5-(2*x-7)', despues: '-2*x-2', espera: 'NO_EQUIVALENTE', nota: 'no reparte el menos' },
  { id: 'di-09', area: 'distributiva', antes: 'x*(x+5)', despues: 'x^2+5*x', espera: 'EQUIVALENTE' },
  { id: 'di-10', area: 'distributiva', antes: 'x*(x+5)', despues: 'x^2+5', espera: 'NO_EQUIVALENTE', nota: 'olvida la x del segundo termino' },
  { id: 'di-11', area: 'distributiva', antes: '3*(2*x-1)+4', despues: '6*x+1', espera: 'EQUIVALENTE' },
  { id: 'di-12', area: 'distributiva', antes: '3*(2*x-1)+4', despues: '6*x+3', espera: 'NO_EQUIVALENTE', nota: 'suma 4 al 3 en vez de al -3' },
  { id: 'di-13', area: 'distributiva', antes: '2*(x+1)+3*(x-2)', despues: '5*x-4', espera: 'EQUIVALENTE' },
  { id: 'di-14', area: 'distributiva', antes: '2*(x+1)+3*(x-2)', despues: '5*x+8', espera: 'NO_EQUIVALENTE', nota: 'signo del segundo parentesis' },
  { id: 'di-15', area: 'distributiva', antes: 'a*(b+c)', despues: 'a*b+a*c', espera: 'EQUIVALENTE' },
  { id: 'di-16', area: 'distributiva', antes: 'a*(b+c)', despues: 'a*b+c', espera: 'NO_EQUIVALENTE', nota: 'distributiva incompleta con letras' },
  { id: 'di-17', area: 'distributiva', antes: '4*(x/2+3)', despues: '2*x+12', espera: 'EQUIVALENTE' },
  { id: 'di-18', area: 'distributiva', antes: '-2*(3-x)', despues: '2*x-6', espera: 'EQUIVALENTE' },
  { id: 'di-19', area: 'distributiva', antes: '-2*(3-x)', despues: '-2*x-6', espera: 'NO_EQUIVALENTE', nota: 'pierde el doble cambio de signo' },
  { id: 'di-20', area: 'distributiva', antes: '(x+1)*3', despues: '3*x+3', espera: 'EQUIVALENTE' },
];

export const PRODUCTOS_NOTABLES: CasoBateria[] = [
  { id: 'pn-01', area: 'productos-notables', antes: '(x+1)^2', despues: 'x^2+2*x+1', espera: 'EQUIVALENTE' },
  { id: 'pn-02', area: 'productos-notables', antes: '(x+1)^2', despues: 'x^2+1', espera: 'NO_EQUIVALENTE', nota: 'el error mas frecuente del temario: falta el doble producto' },
  { id: 'pn-03', area: 'productos-notables', antes: '(x+3)^2', despues: 'x^2+6*x+9', espera: 'EQUIVALENTE' },
  { id: 'pn-04', area: 'productos-notables', antes: '(x+3)^2', despues: 'x^2+9', espera: 'NO_EQUIVALENTE', nota: 'reparte el cuadrado sobre la suma' },
  { id: 'pn-05', area: 'productos-notables', antes: '(x+3)^2', despues: 'x^2+3*x+9', espera: 'NO_EQUIVALENTE', nota: 'doble producto a medias' },
  { id: 'pn-06', area: 'productos-notables', antes: '(x-4)^2', despues: 'x^2-8*x+16', espera: 'EQUIVALENTE' },
  { id: 'pn-07', area: 'productos-notables', antes: '(x-4)^2', despues: 'x^2-8*x-16', espera: 'NO_EQUIVALENTE', nota: 'el cuadrado del negativo es positivo' },
  { id: 'pn-08', area: 'productos-notables', antes: '(x+2)*(x+3)', despues: 'x^2+5*x+6', espera: 'EQUIVALENTE' },
  { id: 'pn-09', area: 'productos-notables', antes: '(x+2)*(x+3)', despues: 'x^2+6', espera: 'NO_EQUIVALENTE', nota: 'solo multiplica primeros por primeros y ultimos por ultimos' },
  { id: 'pn-10', area: 'productos-notables', antes: '(x+2)*(x-2)', despues: 'x^2-4', espera: 'EQUIVALENTE' },
  { id: 'pn-11', area: 'productos-notables', antes: '(x+2)*(x-2)', despues: 'x^2+4', espera: 'NO_EQUIVALENTE', nota: 'signo en la diferencia de cuadrados' },
  { id: 'pn-12', area: 'productos-notables', antes: '(2*x+1)^2', despues: '4*x^2+4*x+1', espera: 'EQUIVALENTE' },
  { id: 'pn-13', area: 'productos-notables', antes: '(2*x+1)^2', despues: '2*x^2+4*x+1', espera: 'NO_EQUIVALENTE', nota: 'no eleva el coeficiente al cuadrado' },
  { id: 'pn-14', area: 'productos-notables', antes: '(a+b)^2', despues: 'a^2+2*a*b+b^2', espera: 'EQUIVALENTE' },
  { id: 'pn-15', area: 'productos-notables', antes: '(a+b)^2', despues: 'a^2+b^2', espera: 'NO_EQUIVALENTE', nota: 'el suenio del novato' },
  { id: 'pn-16', area: 'productos-notables', antes: '(a-b)^2', despues: 'a^2-2*a*b+b^2', espera: 'EQUIVALENTE' },
  { id: 'pn-17', area: 'productos-notables', antes: '(x+1)^3', despues: 'x^3+3*x^2+3*x+1', espera: 'EQUIVALENTE' },
  { id: 'pn-18', area: 'productos-notables', antes: '(x+1)^3', despues: 'x^3+1', espera: 'NO_EQUIVALENTE', nota: 'reparte el cubo' },
  { id: 'pn-19', area: 'productos-notables', antes: '(x-1)*(x^2+x+1)', despues: 'x^3-1', espera: 'EQUIVALENTE' },
  { id: 'pn-20', area: 'productos-notables', antes: '(x+2)*(x-5)', despues: 'x^2-3*x-10', espera: 'EQUIVALENTE' },
  { id: 'pn-21', area: 'productos-notables', antes: '(x+2)*(x-5)', despues: 'x^2+3*x-10', espera: 'NO_EQUIVALENTE', nota: 'signo del termino central' },
  { id: 'pn-22', area: 'productos-notables', antes: '(3*x-2)*(3*x+2)', despues: '9*x^2-4', espera: 'EQUIVALENTE' },
];

export const FACTORIZACION: CasoBateria[] = [
  { id: 'fa-01', area: 'factorizacion', antes: 'x^2+5*x+6', despues: '(x+2)*(x+3)', espera: 'EQUIVALENTE' },
  { id: 'fa-02', area: 'factorizacion', antes: 'x^2+5*x+6', despues: '(x+1)*(x+6)', espera: 'NO_EQUIVALENTE', nota: 'pareja que suma bien pero no multiplica' },
  { id: 'fa-03', area: 'factorizacion', antes: 'x^2-9', despues: '(x-3)*(x+3)', espera: 'EQUIVALENTE' },
  { id: 'fa-04', area: 'factorizacion', antes: 'x^2-9', despues: '(x-3)^2', espera: 'NO_EQUIVALENTE', nota: 'confunde diferencia de cuadrados con trinomio cuadrado' },
  { id: 'fa-05', area: 'factorizacion', antes: 'x^2+9', despues: '(x+3)*(x+3)', espera: 'NO_EQUIVALENTE', nota: 'la suma de cuadrados no factoriza en reales' },
  { id: 'fa-06', area: 'factorizacion', antes: '2*x+4', despues: '2*(x+2)', espera: 'EQUIVALENTE' },
  { id: 'fa-07', area: 'factorizacion', antes: '2*x+4', despues: '2*(x+4)', espera: 'NO_EQUIVALENTE', nota: 'no divide el segundo termino' },
  { id: 'fa-08', area: 'factorizacion', antes: 'x^2-5*x+6', despues: '(x-2)*(x-3)', espera: 'EQUIVALENTE' },
  { id: 'fa-09', area: 'factorizacion', antes: 'x^2-5*x+6', despues: '(x+2)*(x+3)', espera: 'NO_EQUIVALENTE', nota: 'ignora el signo del termino central' },
  { id: 'fa-10', area: 'factorizacion', antes: 'x^2-x-6', despues: '(x-3)*(x+2)', espera: 'EQUIVALENTE' },
  { id: 'fa-11', area: 'factorizacion', antes: 'x^2-x-6', despues: '(x+3)*(x-2)', espera: 'NO_EQUIVALENTE', nota: 'signos cruzados' },
  { id: 'fa-12', area: 'factorizacion', antes: '3*x^2+6*x', despues: '3*x*(x+2)', espera: 'EQUIVALENTE' },
  { id: 'fa-13', area: 'factorizacion', antes: '3*x^2+6*x', despues: '3*x*(x+6)', espera: 'NO_EQUIVALENTE', nota: 'saca factor comun sin dividir' },
  { id: 'fa-14', area: 'factorizacion', antes: 'x^2+2*x+1', despues: '(x+1)^2', espera: 'EQUIVALENTE' },
  { id: 'fa-15', area: 'factorizacion', antes: '4*x^2-25', despues: '(2*x-5)*(2*x+5)', espera: 'EQUIVALENTE' },
  { id: 'fa-16', area: 'factorizacion', antes: '4*x^2-25', despues: '(4*x-5)*(4*x+5)', espera: 'NO_EQUIVALENTE', nota: 'no saca la raiz del coeficiente' },
  { id: 'fa-17', area: 'factorizacion', antes: 'x^3-x', despues: 'x*(x-1)*(x+1)', espera: 'EQUIVALENTE' },
  { id: 'fa-18', area: 'factorizacion', antes: '2*x^2+7*x+3', despues: '(2*x+1)*(x+3)', espera: 'EQUIVALENTE' },
  { id: 'fa-19', area: 'factorizacion', antes: '2*x^2+7*x+3', despues: '(2*x+3)*(x+1)', espera: 'NO_EQUIVALENTE', nota: 'coloca mal los factores del extremo' },
  { id: 'fa-20', area: 'factorizacion', antes: 'a*x+a*y', despues: 'a*(x+y)', espera: 'EQUIVALENTE' },
];
