import type { CasoBateria } from './tipos.js';

/** Aritmetica y fracciones: la base del temario y la mayor fuente de errores. */
export const ARITMETICA: CasoBateria[] = [
  // --- orden de operaciones y signos -----------------------------------
  { id: 'ar-01', area: 'aritmetica', antes: '2+3*4', despues: '14', espera: 'EQUIVALENTE' },
  { id: 'ar-02', area: 'aritmetica', antes: '2+3*4', despues: '20', espera: 'NO_EQUIVALENTE', nota: 'sumo antes de multiplicar' },
  { id: 'ar-03', area: 'aritmetica', antes: '(2+3)*4', despues: '20', espera: 'EQUIVALENTE' },
  { id: 'ar-04', area: 'aritmetica', antes: '10-4-3', despues: '3', espera: 'EQUIVALENTE' },
  { id: 'ar-05', area: 'aritmetica', antes: '10-4-3', despues: '9', espera: 'NO_EQUIVALENTE', nota: 'resto de derecha a izquierda' },
  { id: 'ar-06', area: 'aritmetica', antes: '-3-5', despues: '-8', espera: 'EQUIVALENTE' },
  { id: 'ar-07', area: 'aritmetica', antes: '-3-5', despues: '-2', espera: 'NO_EQUIVALENTE', nota: 'resta en vez de sumar negativos' },
  { id: 'ar-08', area: 'aritmetica', antes: '-3*-5', despues: '15', espera: 'EQUIVALENTE' },
  { id: 'ar-09', area: 'aritmetica', antes: '-3*-5', despues: '-15', espera: 'NO_EQUIVALENTE', nota: 'regla de signos' },
  { id: 'ar-10', area: 'aritmetica', antes: '8-(3-5)', despues: '10', espera: 'EQUIVALENTE' },
  { id: 'ar-11', area: 'aritmetica', antes: '8-(3-5)', despues: '6', espera: 'NO_EQUIVALENTE', nota: 'no distribuyo el menos al segundo termino' },
  { id: 'ar-12', area: 'aritmetica', antes: '2-3*(4-6)', despues: '8', espera: 'EQUIVALENTE' },
  { id: 'ar-13', area: 'aritmetica', antes: '20/4/5', despues: '1', espera: 'EQUIVALENTE' },
  { id: 'ar-14', area: 'aritmetica', antes: '20/4/5', despues: '25', espera: 'NO_EQUIVALENTE', nota: 'divide de derecha a izquierda' },
  { id: 'ar-15', area: 'aritmetica', antes: '100-25*2', despues: '50', espera: 'EQUIVALENTE' },
  { id: 'ar-16', area: 'aritmetica', antes: '100-25*2', despues: '150', espera: 'NO_EQUIVALENTE', nota: 'resto antes de multiplicar' },
  // --- potencias y raices numericas -------------------------------------
  { id: 'ar-17', area: 'aritmetica', antes: '2^3', despues: '8', espera: 'EQUIVALENTE' },
  { id: 'ar-18', area: 'aritmetica', antes: '2^3', despues: '6', espera: 'NO_EQUIVALENTE', nota: 'confunde potencia con producto' },
  { id: 'ar-19', area: 'aritmetica', antes: '(-2)^2', despues: '4', espera: 'EQUIVALENTE' },
  { id: 'ar-20', area: 'aritmetica', antes: '(-2)^3', despues: '-8', espera: 'EQUIVALENTE' },
  { id: 'ar-21', area: 'aritmetica', antes: '(-2)^3', despues: '8', espera: 'NO_EQUIVALENTE', nota: 'exponente impar conserva el signo' },
  { id: 'ar-22', area: 'aritmetica', antes: '3^0', despues: '1', espera: 'EQUIVALENTE' },
  { id: 'ar-23', area: 'aritmetica', antes: '3^0', despues: '0', espera: 'NO_EQUIVALENTE', nota: 'exponente cero da 1, no 0' },
  { id: 'ar-24', area: 'aritmetica', antes: 'sqrt(16)', despues: '4', espera: 'EQUIVALENTE' },
  { id: 'ar-25', area: 'aritmetica', antes: 'sqrt(16)', despues: '8', espera: 'NO_EQUIVALENTE', nota: 'divide entre 2 en vez de sacar raiz' },
  { id: 'ar-26', area: 'aritmetica', antes: 'sqrt(9+16)', despues: '5', espera: 'EQUIVALENTE' },
  { id: 'ar-27', area: 'aritmetica', antes: 'sqrt(9+16)', despues: '7', espera: 'NO_EQUIVALENTE', nota: 'reparte la raiz sobre la suma' },
  { id: 'ar-28', area: 'aritmetica', antes: '2^-2', despues: '1/4', espera: 'EQUIVALENTE' },
  { id: 'ar-29', area: 'aritmetica', antes: '2^-2', despues: '-4', espera: 'NO_EQUIVALENTE', nota: 'exponente negativo no cambia el signo' },
  // --- decimales y porcentajes ------------------------------------------
  { id: 'ar-30', area: 'aritmetica', antes: '0.1+0.2', despues: '0.3', espera: 'EQUIVALENTE', nota: 'clasico de coma flotante: tiene que pasar' },
  { id: 'ar-31', area: 'aritmetica', antes: '1.5*4', despues: '6', espera: 'EQUIVALENTE' },
  { id: 'ar-32', area: 'aritmetica', antes: '0.25*80', despues: '20', espera: 'EQUIVALENTE' },
  { id: 'ar-33', area: 'aritmetica', antes: '0.25*80', despues: '2', espera: 'NO_EQUIVALENTE', nota: 'coma mal colocada' },
  { id: 'ar-34', area: 'aritmetica', antes: '15/100*60', despues: '9', espera: 'EQUIVALENTE' },
  { id: 'ar-35', area: 'aritmetica', antes: '120*1.15', despues: '138', espera: 'EQUIVALENTE' },
  { id: 'ar-36', area: 'aritmetica', antes: '120*1.15', despues: '135', espera: 'NO_EQUIVALENTE', nota: 'suma el 15% del 100 en vez del 120' },
];

export const FRACCIONES: CasoBateria[] = [
  { id: 'fr-01', area: 'fracciones', antes: '1/2+1/3', despues: '5/6', espera: 'EQUIVALENTE' },
  { id: 'fr-02', area: 'fracciones', antes: '1/2+1/3', despues: '2/5', espera: 'NO_EQUIVALENTE', nota: 'suma numeradores y denominadores' },
  { id: 'fr-03', area: 'fracciones', antes: '2/4+1/3', despues: '10/12', espera: 'EQUIVALENTE' },
  { id: 'fr-04', area: 'fracciones', antes: '2/4+1/3', despues: '3/7', espera: 'NO_EQUIVALENTE', nota: 'suma cruzada' },
  { id: 'fr-05', area: 'fracciones', antes: '10/12', despues: '5/6', espera: 'EQUIVALENTE' },
  { id: 'fr-06', area: 'fracciones', antes: '10/12', despues: '5/3', espera: 'NO_EQUIVALENTE', nota: 'simplifica solo el numerador' },
  { id: 'fr-07', area: 'fracciones', antes: '3/4-1/6', despues: '7/12', espera: 'EQUIVALENTE' },
  { id: 'fr-08', area: 'fracciones', antes: '3/4-1/6', despues: '2/2', espera: 'NO_EQUIVALENTE', nota: 'resta numeradores y denominadores' },
  { id: 'fr-09', area: 'fracciones', antes: '2/3*3/5', despues: '6/15', espera: 'EQUIVALENTE' },
  { id: 'fr-10', area: 'fracciones', antes: '2/3*3/5', despues: '2/5', espera: 'EQUIVALENTE', nota: 'simplificado, tambien correcto' },
  { id: 'fr-11', area: 'fracciones', antes: '2/3*3/5', despues: '10/9', espera: 'NO_EQUIVALENTE', nota: 'multiplica en cruz' },
  { id: 'fr-12', area: 'fracciones', antes: '(2/3)/(4/5)', despues: '10/12', espera: 'EQUIVALENTE' },
  { id: 'fr-13', area: 'fracciones', antes: '(2/3)/(4/5)', despues: '8/15', espera: 'NO_EQUIVALENTE', nota: 'multiplica en vez de invertir' },
  { id: 'fr-14', area: 'fracciones', antes: '1/2+1/4+1/8', despues: '7/8', espera: 'EQUIVALENTE' },
  { id: 'fr-15', area: 'fracciones', antes: '1/2+1/4+1/8', despues: '3/14', espera: 'NO_EQUIVALENTE', nota: 'suma todo en linea' },
  { id: 'fr-16', area: 'fracciones', antes: '5/8-3/8', despues: '2/8', espera: 'EQUIVALENTE' },
  { id: 'fr-17', area: 'fracciones', antes: '5/8-3/8', despues: '2', espera: 'NO_EQUIVALENTE', nota: 'resta numeradores y tira el denominador' },
  { id: 'fr-18', area: 'fracciones', antes: '2+1/3', despues: '7/3', espera: 'EQUIVALENTE' },
  { id: 'fr-19', area: 'fracciones', antes: '2+1/3', despues: '3/3', espera: 'NO_EQUIVALENTE', nota: 'suma el entero al numerador sin convertir' },
  { id: 'fr-20', area: 'fracciones', antes: '1/(1/4)', despues: '4', espera: 'EQUIVALENTE' },
  { id: 'fr-21', area: 'fracciones', antes: '1/(1/4)', despues: '1/4', espera: 'NO_EQUIVALENTE', nota: 'no invierte' },
  { id: 'fr-22', area: 'fracciones', antes: '(1/2)^2', despues: '1/4', espera: 'EQUIVALENTE' },
  { id: 'fr-23', area: 'fracciones', antes: '(1/2)^2', despues: '2/4', espera: 'NO_EQUIVALENTE', nota: 'eleva solo el denominador' },
  { id: 'fr-24', area: 'fracciones', antes: '(x+1)/2+(x-1)/2', despues: 'x', espera: 'EQUIVALENTE' },
  { id: 'fr-25', area: 'fracciones', antes: '(x+1)/2+(x-1)/2', despues: '2*x', espera: 'NO_EQUIVALENTE', nota: 'olvida el denominador comun' },
  { id: 'fr-26', area: 'fracciones', antes: '(x+2)/2', despues: 'x/2+1', espera: 'EQUIVALENTE' },
  { id: 'fr-27', area: 'fracciones', antes: '(x+2)/2', despues: 'x+1', espera: 'NO_EQUIVALENTE', nota: 'cancela el 2 solo con el 2' },
  { id: 'fr-28', area: 'fracciones', antes: '(2*x)/(2*y)', despues: 'x/y', espera: 'EQUIVALENTE' },
  { id: 'fr-29', area: 'fracciones', antes: '(x^2-1)/(x-1)', despues: 'x+1', espera: 'EQUIVALENTE', nota: 'racional: la capa 2 lo resuelve exacto' },
  { id: 'fr-30', area: 'fracciones', antes: '(x^2-1)/(x-1)', despues: 'x-1', espera: 'NO_EQUIVALENTE', nota: 'factoriza con el signo cambiado' },
  { id: 'fr-31', area: 'fracciones', antes: '(x+1)/(x^2-1)', despues: '1/(x-1)', espera: 'EQUIVALENTE' },
  { id: 'fr-32', area: 'fracciones', antes: '1/x+1/y', despues: '(x+y)/(x*y)', espera: 'EQUIVALENTE' },
  { id: 'fr-33', area: 'fracciones', antes: '1/x+1/y', despues: '1/(x+y)', espera: 'NO_EQUIVALENTE', nota: 'el clasico: suma denominadores' },
];
